### ISSUE TITLE
Using regular .Vue Structure?

### ISSUE THREAD

**Issue by ccrvlh** [arswaw/VueSpaNONODE#2]
Hi there.
Thanks for you blog post, I've been looking for a way to work with my apps with the node_modules nightmare for a while now.
I was wondering if there's a way to deal with this project structure while keeping the `App.vue` kind of pattern, meaning:

```
<template>
<div id="component"></div>
</template>

<script>

export default {
    data(){
        return {
            }
     }
}

</script>
```

I tried using a App.vue component, but I've been getting an error on Firefox while serving my app with a Flask development server, so I wonder if that's even possible...

`Loading module from “http://localhost:5000/static/App.vue” was blocked because of a disallowed MIME type (“application/octet-stream”).`

Thanks!

**Comment by arswaw** [comment]
@lowercase00 

Hi, thank you for reading my blog post. I'm glad it's helping so many people.

The short version is probably not, but it wouldn't take too long for me to write a script. What OS are you using?

### The long version is this:

One thing to note is that through the "template" in the vue component can use HTML with ES6 multiline strings. Here is an example:

`const MySuperVueComponent = {
    template: ``<h1>Super Vue!</h1>``
}`

Markdown makes it difficult for me to show this, but you only need one set of backticks around the HTML. I haven't yet figured out how to make CSS work unless you write it inline with the HTML, or use VueJS. For example you could specify a class in the data key, and then in the HTML, call a method, or write an expression that will call in a specific CSS class. This will keep HTML, CSS, and JS in one file without transpilation. Is that your goal? I can expand on how to do any of these if needed.

### The even longer version is this:

.Vue components are generally created with the Vue CLI. This of course uses Node.js so we which we'd like to avoid. The easiest way to use these is to install the Vue CLI globally and work with the command line. This does add a build step to your project, because under the hood, Vue CLI is using Webpack + [vue-loader](https://github.com/vuejs/vue-loader).

It will never work natively, but you might still be able to avoid having to use node_modules or a package.json in your project with just command line tools.

This isn't how it's meant to be used, and the best way to deal with these projects is for someone to write a script that works with Linux and Windows. This script would work without the use of anything Node.js in order to compile each .Vue component into one .html, one .js, and one .css file per folder.

You would have a trigger that runs the script on every save. This ensures that you won't have to deal with Node.js at all, and you still have your .Vue components. The only downside is that you would have to attach each .css file to the main index.html file. I'm not sure if any way around that at the moment. I will look into writing the script though.

Does this explanation help at all?

**Comment by ccrvlh** [comment]
Hey Alex, thanks a lot.
Coming from Python I confess this whole Javascript and Frameworks world is very confusing to me. It's hard to understand why a one-page project starts with +100MB worth of modules...
My main object is to actually be able to use VueJS within Flask's template folder, leveraging the nice integration Flask + Jinja offers with the power of VueJS.

So I imagined a similar 'traditional' VueJS strutucture (`app.js`, `App.vue`, `components` folder), all within my `static` folder (which is within my `app` folder - the main Flask folder).

But everywhere I read about it I get that strange format, where I have to write HTML as a string, which does not seem very natural at first. From what you're saying, the structure I'm imagining is not possible without the +100MB (atm is at about 140MB) worth of `node_modules` within my project, and having to start two different servers (Flask and VueJS).

Anyways, thanks a lot for taking your time to explaining the challenges involved!

**Comment by arswaw** [comment]
@lowercase00 There were some decisions made when Node.js first arrived that led to these dependency issues. You can't have .Vue specifically, but as you pointed out there are ways to contain the HTML + CSS + JS in one file without the 100MB dependencies.

You can use Vue without the .Vue components using this repo.

Thanks for opening the issue, and thanks for using my template.
